# Generated by Django 5.2.9 on 2025-12-09 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_enforce_qc_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('thumbnail_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_type', models.CharField(choices=[('image', 'Screenshot'), ('video', 'Video')], default='image', max_length=10)),
                ('confidence_score', models.FloatField(blank=True, help_text='Model confidence score (0-1)', null=True)),
                ('detection_data', models.JSONField(blank=True, help_text='Additional detection data (bounding boxes, coordinates, etc.)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed'), ('false_positive', 'False Positive'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('detected_at', models.DateTimeField(help_text='When the detection occurred (from camera timestamp)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the record was saved to database')),
                ('viewed', models.BooleanField(default=False)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin/user notes')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_records', to='camera.camera')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_records', to=settings.AUTH_USER_MODEL)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_records', to='camera.feature')),
            ],
            options={
                'db_table': 'detectionRecord',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['camera', '-detected_at'], name='detectionRe_camera__3264b9_idx'), models.Index(fields=['customer', '-detected_at'], name='detectionRe_custome_b385c4_idx'), models.Index(fields=['feature', '-detected_at'], name='detectionRe_feature_ebd738_idx'), models.Index(fields=['status', '-detected_at'], name='detectionRe_status_e32f21_idx'), models.Index(fields=['viewed', '-detected_at'], name='detectionRe_viewed_be9772_idx')],
            },
        ),
    ]
