# Generated by Django 5.2.9 on 2025-12-09 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_detectionrecord'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""DROP TRIGGER prevent_manual_lock_trigger on camera
            """,
        )
    ]
